### ISSUE TITLE
WP1 - Auswählen geeigneter Daten

### ISSUE THREAD

**Issue by LisaRei** [tuwien-geoweb-2015/g04_projekt#1]
DATEN:

Verkehr:
Bereits aufbereitete Daten: 

• Aktive Mobilität

 Radwege
 Citybikestationen
 Fahrradabstellplätze
 Fußgängerzonen

• Öffentlicher Verkehr

 Schnellbahnen: Linien und Haltestellen
 U- Bahn: Linien und Haltstellen
 Haltestellen Bus und Straßenbahn

Demografie:

Bereits aufbereitete Daten 
Daten nach Bezirke

Bevölkerungsdichte

Bevölkerung Struktur:
 Anteil Männlich
 Anteil Weiblich
 Anteil österreichische Staatsbürger
 Geburtenrate
 Anteil erwerbsfähiger Bevölkerung
 Anteil Jugendlicher <18
 Anteil Erwachsener 18-65
 Anteil Senioren >65

für schönere Ansicht siehe Word: 
[Daten.docx](https://github.com/tuwien-geoweb-2015/g04_ue/files/44890/Daten.docx)

**Comment by MatthaeusMarte** [comment]
Wir müssen noch für die Demografie geeignete Daten finden! damit wir die Daten beim nächsten Milestone verarbeiten können und in die Datenbank exportieren können.

**Comment by dominik1990** [comment]
Erledigt!
