### ISSUE TITLE
WP2 Programmierung für das Web I

### ISSUE THREAD

**Issue by MatthaeusMarte** [tuwien-geoweb-2015/g04_projekt#10]
Verbesserung der groben Strukturen

**Comment by MatthaeusMarte** [comment]
@ahocevar 
sehr geehrter herr hocevar, 
unsere applikation ist eigentlich fast fertig, jedoch wollen wir unseren layern noch eine Hierarchie geben..
![image](https://cloud.githubusercontent.com/assets/15378013/12180272/e6275aca-b57b-11e5-8e59-49bba9718c21.png)
das problem ist, dass sie sich überlappen, erst bei erneutem klicken kommen sie an die oberste stelle....
wir haben schon viel gegoogelt und im internet gesucht... wissen jedoch nicht wirklich wie man das macht... möglicherweise gibt es auch ein z-index im javascript?
wir haben unsere derzeitige app auf github geladen (siehe linke: https://github.com/tuwien-geoweb-2015/g04_projekt/tree/master/wien_map ), wir wären froh wenn sie uns bezüglich der layer hierarchie weiterhelfen bzw. einen tipp geben könnten
lg g04

**Comment by ahocevar** [comment]
Mein Vorschlag wäre, z.B. statt `olMap.addLayer(CITYBIKE_stationen)` und `olMap.removeLayer(CITYBIKE_stationen)` folgendes zu verwenden:

``` js
CITYBIKE_stationen.setVisible(false);
CITYBIKE_stationen.setVisible(true);
```

Alternative geht natürlich auch `zIndex`, siehe http://openlayers.org/en/v3.12.1/apidoc/ol.layer.Base.html#setZIndex bzw. die `zIndex` Option für Layer, z.B.

```
var CITYBIKE_stationen = new ol.layer.Image({
  zIndex: 4,
  source: new ol.source.ImageWMS({
    url: 'http://student.ifip.tuwien.ac.at/geoserver/wms',
    params: {'LAYERS': 'g04_2015:CITYBIKE_stationen'}
  }),
});
```
