### ISSUE TITLE
WP0 - Gestalterische Bearbeitung

### ISSUE THREAD

**Issue by MatthaeusMarte** [tuwien-geoweb-2015/g04_projekt#12]
Symbole, Layout, Icons

**Comment by MatthaeusMarte** [comment]
Symbole, Standortmarker, bzw icons für:
 Radwege
 Citybikestationen
 Fahrradabstellplätze
 Fußgängerzonen

 Schnellbahnen: Linien und Haltestellen
 U- Bahn: Linien und Haltstellen
 Haltestellen Bus und Straßenbahn

![image](https://cloud.githubusercontent.com/assets/15378013/11653445/932ee486-9d9e-11e5-9ed9-66585d31e9e9.png)

schlicht und einfach, soll gut ausschauen ;)

**Comment by dominik1990** [comment]
Icons wurden entworfen, und sind nun auf Github, sowie DP!
