### ISSUE TITLE
WP1 - Erstellung einer Datenbank

### ISSUE THREAD

**Issue by LisaRei** [tuwien-geoweb-2015/g04_projekt#6]

**Comment by MatthaeusMarte** [comment]
@ahocevar Sehr geehrter Herr Hocevar, wir haben bei der Erstellung der SpatiaLite db ein Problem, ich hoffe sie können uns helfen. wir haben sreenshots der situation gemacht, vielleicht könnten sie einen blick drauf werden, wir wollten das Shapefile der Bezirksgrenzen dazuladen, aber die eingegebenen eigenschaften scheinen nicht zu stimmen. utf-8 funktioniert nicht die anderen charset encoding schon. lg g04 
![image](https://cloud.githubusercontent.com/assets/15378013/11557374/b230af54-99ac-11e5-9242-85f22ba80d73.png)
![image](https://cloud.githubusercontent.com/assets/15378013/11557383/b8a659f6-99ac-11e5-89d6-0b02288061e4.png)
![image](https://cloud.githubusercontent.com/assets/15378013/11557391/c0e0cec6-99ac-11e5-8fe5-101dab58688c.png)

**Comment by MatthaeusMarte** [comment]
@ahocevar Sehr geehrter Herr Hocevar, wir konnten das erste Problem mit dem utf-8 Encoding lösen indem wir das shape ins QGIS geladen haben und dann als utf-8 abgespreichert haben, wir sind jedoch beim nächsten problem angelangt, wir schaffen es nicht die demografie daten an die Bezirksshapes zu joinen... wir werden aus den tutorial unterlagen bzw aus den vorlesungsunterlagen nicht besonders schlau... ich hoffe sie können uns weiterhelfen lg g04
![image](https://cloud.githubusercontent.com/assets/15378013/11559064/9616625a-99b6-11e5-96b0-8cc5768e225b.png)

**Comment by ahocevar** [comment]
Zum ersten Problem: schön, dass ihr es über QGIS geschafft habt. Direkt wäre es auch gegangen, mit Auswählen von "ISO-8859-1" anstatt "UTF-8" als Encoding.

Zum zweiten Problem: wenn ihr den Join so macht, wie im census map Beispiel, erfolgt dieser direkt im SQL-Statement, das ihr in GeoServer eingebt. Erinnert euch, wie wir die census Tabelle mit den counties Geometrien verknüpft haben. Zwei kleine Hinweise:
- Der Join braucht in beiden Tabellen den Bezirkscode
- ' %column%'  funktioniert nur in GeoServer, nicht in SpatiaLiteGUI. Dort müsst ihr stattdessen einen Spaltennamen aus der Demographie-Tabelle explizit angeben.

**Comment by MatthaeusMarte** [comment]
Die Daten wurden so strukturiert, dass sie eigentlich gut zu joinen sind, die daten sollten über den die Variable BEZNR gejoint werden können. siehe einerseits demographie daten ->
![image](https://cloud.githubusercontent.com/assets/15378013/11563690/8550edcc-99d5-11e5-84c8-c0a57241d13e.png)
siehe Bezirksgrenzen ->
![image](https://cloud.githubusercontent.com/assets/15378013/11563723/b35ae114-99d5-11e5-9a90-89251b861a28.png)

wir haben zwar das census beispiel in block6 aktiv mitgemacht, allerdings können wir uns am besten willen kaum mehr daran erinnern, wie der join ablief und wie es in geoserver nochmals hochgeladen wurde. wir können uns nur noch daran erinnern, dass sie zwischen dem tutorial census map und zwischen den vorlesungsunterlagen hin und her gesprungen sind und nicht immer die codes verwendet haben, die im census map tutorial sind. ohne schritt für schritt anleitung können wir die Vorgehensweise kaum mehr rekonstruieren. lg g04

**Comment by ahocevar** [comment]
Siehe http://ahocevar.net/tuwien-geoweb/block6.html#/5 für das komplette SQL für GeoServer. Zum Testen im SQLiteAdmin muss `%column%`  durch einen Spaltennamen ersetzt werden, also z.B. `DISTRICT_POP`.

`census` muss durch euren Tabellannamen der Demografiedatentabelle ersetzt werden. `fips` durch `BEZNR`.

Und dann sollte es eigentlich schon funktionieren.

**Comment by MatthaeusMarte** [comment]
wir denken wir müssen die SQL Befehle im SpatialLitegui eingeben. irgendwie verstehen wir das so, dass zuerst im SpatiaLitegui die Daten verbunden werden und dann auf Geoserver geladen wird. irgendwie klingt das bei ihnen so, als ob die SQL Befehle auch im Geoserver eingegeben werden?!? (Verwirrung). Wenn ja wird der Code doch im SpatiaLitegui eingegeben und angepasst -> census wird durch unsere demografie tabelle ersetzt und counties durch unser OGD Bezirksgrenzen shapefile, und schließlich fips mit BEZNR? ist das so korrekt? und dann wird die datenbank auf dem webspace abgespeichert und auf geoserver geladen?

**Comment by ahocevar** [comment]
Korrekt. Und in GeoServer wird dann beim Erstellen des Layers "Create from SQL view" ausgewählt, und dort wird der komplette SQL-Befehl mit dem Join und den `%column%` Variablen eingegeben.

Zur Erklärung: das ist kein Join, der eine Tabelle erzeugt, sondern der wird jedesmal aufgerufen, wenn GeoServer Daten von SpatiaLite anfordert.

**Comment by MatthaeusMarte** [comment]
das angepasste SQL statement sollte dann etwa so aussehen?
ist der output im unteren fenster korrekt? 
![image](https://cloud.githubusercontent.com/assets/15378013/11566705/d811afc0-99e3-11e5-8bca-9354488453a2.png)

**Comment by ahocevar** [comment]
Ja, dann müsst ihr NAMEK verwenden. Zur Erklärung:

```
counties.name || ' County' AS name,
```

bedeutet: nimm den Namen aus der Tabelle, füge ' County' dran, und mach das ganze als Layer-Attribut 'name' verfügbar. Also z.B. aus "Frederick" würde dann "Frederick County" werden. Wahrscheinlich wird bei euch etwas in der Art reichen:

```
bezirke.NAMEK AS name
```

**Comment by MatthaeusMarte** [comment]
das angepasste SQL statement sollte dann etwa so aussehen?
ist der output im unteren fenster korrekt? 
![image](https://cloud.githubusercontent.com/assets/15378013/11567312/c2482f04-99e6-11e5-84df-d630f1a70ced.png) 
anschließend wird die datenbank in den webspace geladen und in geoserver geladen und entsprechend editiert?

**Comment by ahocevar** [comment]
Ja, schaut gut aus.
