### ISSUE TITLE
WP2 - Vorbereitungen im Geoserver

### ISSUE THREAD

**Issue by LisaRei** [tuwien-geoweb-2015/g04_projekt#7]

**Comment by MatthaeusMarte** [comment]
@ahocevar beim erstellen der sql view in geoserver, kommen diese Probleme auf... wir glauben, dass die eingaben fast richtig sind, aber es gibt offensichtlich noch einen fehler... könnten sie mal einen blick drauf werfen? ist es egal was im fenster view name eingetragen wird? offensichtlich scheinen "%" zeichen für fehler.. lg g04
![image](https://cloud.githubusercontent.com/assets/15378013/11589444/ed0f69d0-9a88-11e5-84a1-8639fc9ccb63.png)

![image](https://cloud.githubusercontent.com/assets/15378013/11589475/27c25376-9a89-11e5-9ef0-a8b6eb2872a6.png)

**Comment by ahocevar** [comment]
Ihr müsst die SQL View Parameter und Attribute vorschlagen lassen und einen Standardwert festlegen, so wie im Census Map Tutorial beschrieben.
