### ISSUE TITLE
WP1 Programmierung für das Web

### ISSUE THREAD

**Issue by MatthaeusMarte** [tuwien-geoweb-2015/g04_projekt#9]
html, css, javascript, grobe Struktur der Applikation

**Comment by MatthaeusMarte** [comment]
@ahocevar 
sehr geehrter herr hocevar,

wir versuchen schon die längste zeit bei der dropdown liste ein topic mit einem leeren Layer anzulegen.. sodass, wenn die seite aufgeht kein layer sichtbar ist, erst wenn man auf das entsprechende topic klickt, es schein fast zu funktionieren, nur der layer erscheint schon wenn das topic ---leer--- ausgewählt ist, erst bei erneutem anklicken verschwindet er. außerdem scheint die leiste mit der suchfunktion plötzlich nicht mehr zu funktionieren.

![image](https://cloud.githubusercontent.com/assets/15378013/11779552/2d83814c-a25c-11e5-9e63-7c1804a61376.png)

wir haben dazu die liste nicht mittels dem DataDict gemacht sondern im html 
![image](https://cloud.githubusercontent.com/assets/15378013/11779409/3bffff76-a25b-11e5-96d3-54699c1ab9b9.png)

wir haben allerdings schwierigkeiten wenn wir die topics mit javascript verknüpfen wollen. mit diesem  befehl scheint es fast zu funktionieren, nur dass die oben gennanten probleme auftuauchen. 
![image](https://cloud.githubusercontent.com/assets/15378013/11779445/7675a8a4-a25b-11e5-995f-05174933ebd6.png)

wir haben die dateien auf github geladen, wir wären froh wenn sie mal einen Blick drauf werfen könnten. https://github.com/tuwien-geoweb-2015/g04_projekt/tree/master/wien_test
lg g04

**Comment by ahocevar** [comment]
Ich schau's mir jetzt gerade an.

**Comment by ahocevar** [comment]
Damit beim Laden der WMS Layer nicht gezeigt wird, müsst ihr [hier](https://github.com/tuwien-geoweb-2015/g04_projekt/blob/master/wien_test/censusmap.js#L19) `, wmsLayer` entfernen.

**Comment by ahocevar** [comment]
Und was genau funktioniert bei der Suchfunktion nicht?

**Comment by MatthaeusMarte** [comment]
Danke für die schnelle rückmeldung, es hat funktioniert! bei der suchfunktion lässt er mich nicht nach orten suchen... weiß nicht woran das liegt...

**Comment by ahocevar** [comment]
Eure Karte heißt `map`, aber ihr referenziert sie an mehreren Stellen als [`olMap`](https://github.com/tuwien-geoweb-2015/g04_projekt/search?utf8=✓&q=olMap). Ändert diese Stellen einfach auf `map`.
